<?php
/** @var $block \Ashsmith\Blog\Block\PostView */
/** @var $blog \Ashsmith\Blog\Model\Blog */
$blog = $block->getBlog();
?>
<div class="navigation"><a href="."><?php echo __('&lt;- Back') ?></a></div>
<h1 class="blog-post-item-title"><?php echo $blog->getTitle() ?></h1>

<div class="blog-post-item-content">
    <?php echo $blog->getContent(); ?>
</div>

<div class="blog-post-item-meta">
    <strong><?php echo __('Created at:') ?></strong> <?php echo $blog->getCreationTime() ?>
</div>