<?php /** @var $block \Windigo\Blog\Block\BlogList */ ?>
<h1><?php echo __('Latest Blog Blogs') ?></h1>
<div class="row">
	
<?php /** @var $blog \Windigo\Blog\Model\Blog */ ?>
<?php foreach ($block->getBlogs() as $blog): ?>
    <div class="col-xl-6 col-md-12 blog-blog-list-item">
        <h3 class="blog-blog-item-title">
            <a href="<?php echo $blog->getUrl() ?>"><?php echo $blog->getTitle() ?></a>
        </h3>

        <div class="blog-blog-item-content">
            <?php echo $blog->getContent(); ?>
        </div>

        <div class="blog-blog-item-meta">
            <strong><?php echo __('Created at:') ?></strong> <?php echo $blog->getCreationTime() ?>
        </div>
    </div>
<?php endforeach; ?>
</div>